---

- name: Create a snapshot image of the created container
  hosts: localhost
  vars_files:
  - 0-config.yaml
  run_once: true
  tasks:
    - name: Commit container
      command: docker commit {{docker_container_name}} {{docker_image_name}}
