---

# Inspired by "Docker without Dockerfiles",
# https://tech.labs.oliverwyman.com/blog/2019/08/30/docker-without-dockerfiles/

- hosts: localhost

- import_playbook: docker-container.yaml
- import_playbook: docker-playbook.yaml
- import_playbook: docker-commit.yaml
