---

#################################################################################
# Inspired by "Docker without Dockerfiles",                                     #
# https://tech.labs.oliverwyman.com/blog/2019/08/30/docker-without-dockerfiles/ #
#################################################################################

- hosts: localhost

- import_playbook: 1-preconditions-check.yaml
- import_playbook: 2-docker-container.yaml
- import_playbook: 3-docker-playbook.yaml
- import_playbook: 4-docker-commit.yaml
